import type { Metadata } from "next";
import { EmotionRegistry } from "../components/EmotionRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <EmotionRegistry options={{ key: "css" }}>{children}</EmotionRegistry>
      </body>
    </html>
  );
}
